language: ruby
rvm:
  - 2.3
  - jruby
before_install:
  - gem install bundler
  - bundle _2.0.2_ install

before_script:
  - bundle update --bundler
script:   
  - gem install bundle
  - bundle exec rake
