language: ruby
rvm:
  - 2.6.1
  - jruby
before_install:
  - gem install rails
  - gem update --system
  - gem install bundler
  - bundle install

before_script:
  - bundle update --bundler
script:   
  - gem install bundle
  - bundle exec rake
