language: ruby
rvm:
  - 2.6.1
  
before_install:
  - gem install rails
  - gem update --system
  - gem install bundler
  - sudo apt-get install libpq-dev
  # - gem install pg -v '1.1.4' --source 'https://rubygems.org/'
  - bundle install

services:
  - postgresql