env:
  global:
    - CC_TEST_REPORTER_ID=ABC123

language: ruby
rvm:
  - 2.6.1

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - bundle exec rspec
  
before_install:
  - gem install rails
  - gem update --system
  - gem install bundler
  - sudo apt-get install libpq-dev
  - psql -c 'create database my_database_development;' -U postgres
  - psql -c 'create database my_database_test;' -U postgres
  - psql -c 'create database my_database_production;' -U postgres
  # - gem install pg -v '1.1.4' --source 'https://rubygems.org/'
  - bundle install

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

services:
  - postgresql